[package]
name = "cgroup_mem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.24.0"
tui-tree-widget = "0.15.0"
crossterm = "0.27"
clap = { version = "4.4.11", features = ["derive"] }
