[package]
name = "cgroup_mem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
tui-tree-widget = "0.11.0"
crossterm = "0.25"
clap = { version = "4.0.9", features = ["derive"] }
